### PR TITLE
David-Feature: Adding FE Migration Scripts + clean up

### PR DESCRIPTION
**Pull request by W3stside**
1. Adds `src/migrations/` to root holding migrations logic separated from main migrations (as `dx-contracts` does and allows FE to pull in deps + migrate/compile contracts outside the main repo)
2. Clean up on `4_deploy_pool` logic
3. Pinned `dx-contracts` `util-contracts` `gno-token` to versions `2.0.0`, respectively

### CODE REVIEW

**Comment by W3stside** [comment]
eslint edits I made as I was annoyed of squigly red lines but lemme know if you'd like me to revert them; I think it's just an add for recognizing `process` from `node` (not sure why it's not recognized on my IDE in your repo)

**Comment by fleupold** [comment]
What exactly does FE mean?

**Comment by W3stside** [comment]
donezo! :+1: @fleupold it's frontend but in this case it wasn't really frontend specific at all :sweat_smile:

**Comment by W3stside** [comment]
I'll let you guys merge :+1: Could someone `RC2` and publish? Thanks

**Pull request merged**
